### ISSUE TITLE
Weekend is different for different countries

### ISSUE THREAD

**Issue by dickclaus** [watson/is-it-weekend#1]
For example in Israel people work from Sunday to Thursday
https://en.wikipedia.org/wiki/Workweek_and_weekend

**Comment by watson** [comment]
Ah, good point. Never considered that.

I guess we need to change the API to allow you to say which country you are in or something.

Probably something like providing an optional country code as the only argument:

```js
var bool = weekend([country-code])
```

**Comment by watson** [comment]
Published in v1.1.0 👍
